#!/bin/bash

#Allow loopback device (internal communication)
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

#Allow all local traffic.
iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT
iptables -A OUTPUT -d 192.168.1.0/24 -j ACCEPT

#Allow VPN establishment
iptables -A OUTPUT -o wlp3s0 -p udp --dport 1194 -j ACCEPT
iptables -A INPUT -i wlp3s0 -p udp --sport 1194 -j ACCEPT

#Accept all TUN connections (tun = VPN tunnel)
iptables -A OUTPUT -o tun0 -j ACCEPT
iptables -A INPUT -i tun0 -j ACCEPT

#Allow dns connection
iptables -A OUTPUT -p udp -o wlp3s0 --dport 53 -j ACCEPT
iptables -A INPUT -p udp -i wlp3s0 --sport 53 -j ACCEPT

#Set default policies to drop all communication unless specifically allowed
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
