#!/bin/bash
# back up to offsite server
rsync -avzh --stats -e ssh shannon@millers.ltd:/hdd2/MAS90-backup/ /media/data/ > /tmp/remote-backup-log.txt
echo "Here is today's MAS 90 remote backup log file." | mail -s "Backup Log" -a /tmp/remote-backup-log.txt shannon@lightbulbsdirect.com 
