#!/bin/bash

## set up routing rules to forward certain ports to lxc containers
iptables -t nat -A POSTROUTING -p tcp -d 192.168.1.131 --dport 4040 -j SNAT --to-source 192.168.1.133
iptables -t nat -A PREROUTING -p tcp --dport 11225 -j DNAT --to-destination 192.168.1.131:4040
