#!/bin/bash
 
# Get the container list
cts="$(lxc-ls --active)"
 
# Update each containers
update_ct(){
        local ct="$1"
        echo "-- [Container: $ct [$(hostname) @ $(date)] ] --"
        /usr/bin/lxc-attach -n "$ct" apt-get -- -qq update
        /usr/bin/lxc-attach -n "$ct" apt-get -- -qq -y upgrade
        /usr/bin/lxc-attach -n "$ct" apt-get -- -qq -y clean
        /usr/bin/lxc-attach -n "$ct" apt-get -- -qq -y autoclean 
        echo "************************************************************"
}
 
# Do it
for c in $cts
do
   update_ct "$c"
done
